# Generated by Django 4.2.4 on 2023-10-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_bible', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadprogress',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
