# Generated by Django 4.2.4 on 2023-10-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_bible', '0002_roadprogress_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defaultmode', models.CharField(default='randomword', max_length=255)),
                ('color', models.CharField(default='#3876d2', max_length=255)),
                ('translation', models.CharField(default='NIV', max_length=255)),
            ],
        ),
    ]
