# Generated by Django 4.2.4 on 2023-10-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_bible', '0003_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='user_name',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
