# Generated by Django 4.2.4 on 2023-10-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_bible', '0004_settings_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRoads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verses', models.JSONField()),
            ],
        ),
    ]
