# Generated by Django 4.2.4 on 2023-11-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_bible', '0006_customroads_creator_customroads_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('index', models.PositiveIntegerField(default=0)),
                ('user_name', models.CharField(max_length=255)),
                ('road', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='settings',
            name='translation',
            field=models.CharField(default='NLT', max_length=255),
        ),
    ]
