# Generated by Django 4.2.4 on 2023-11-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_bible', '0007_favorites_alter_settings_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='verse',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
