# Generated by Django 4.2.4 on 2023-11-20 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_bible', '0008_favorites_verse'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadprogress',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
