# Generated by Django 4.2.4 on 2023-12-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_bible', '0009_roadprogress_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadprogress',
            name='isCustom',
            field=models.BooleanField(default=False),
        ),
    ]
