# Generated by Django 4.2.4 on 2023-12-06 20:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('road_bible', '0010_roadprogress_iscustom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadprogress',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
