# Generated by Django 4.2.4 on 2023-12-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_bible', '0012_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='userid',
            field=models.CharField(default='NONE', max_length=255),
        ),
    ]
